# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config  -ruleid {10}  -id {Place 30-568}  -suppress 
set_msg_config  -ruleid {11}  -id {Place 46-29}  -string {{WARNING: [Place 46-29] place_design is not in timing mode. Skip physical synthesis in placer}}  -suppress 
set_msg_config  -ruleid {12}  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraint will be written out.}}  -suppress 
set_msg_config  -ruleid {13}  -id {Vivado 12-1017}  -string {{WARNING: [Vivado 12-1017] Problems encountered:
1. Failed to delete one or more files in run directory C:/Users/bup48/Documents/VivadoProjects/RISCPROCESSOR-8/RISCPROCESSOR-8.runs/synth_1}}  -suppress 
set_msg_config  -ruleid {14}  -id {Power 33-232}  -string {{WARNING: [Power 33-232] No user defined clocks were found in the design!
Resolution: Please specify clocks using create_clock/create_generated_clock for sequential elements. For pure combinatorial circuits, please specify a virtual clock, otherwise the vectorless estimation might be inaccurate}}  -suppress 
set_msg_config  -ruleid {15}  -id {Timing 38-313}  -suppress 
set_msg_config  -ruleid {4}  -id {Synth 8-85}  -suppress 
set_msg_config  -ruleid {5}  -id {Synth 8-6026}  -string {{WARNING: [Synth 8-6026] Ignoring keep related attribute (keep/mark_debug/dont_touch) applied on memory [C:/Users/bup48/Downloads/data_memory.v:11]}}  -suppress 
set_msg_config  -ruleid {6}  -id {Vivado 12-584}  -string {{WARNING: [Vivado 12-584] No ports matched 'mclk'. [C:/Users/bup48/Downloads/nexys4_ddr.xdc:2]}}  -suppress 
set_msg_config  -ruleid {7}  -id {Vivado 12-584}  -string {{WARNING: [Vivado 12-584] No ports matched 'mclk'. [C:/Users/bup48/Downloads/nexys4_ddr.xdc:3]}}  -suppress 
set_msg_config  -ruleid {8}  -id {Synth 8-6014}  -string {{WARNING: [Synth 8-6014] Unused sequential element uut/SSEG_CA_reg was removed.  [C:/Users/bup48/Downloads/master.v:162]}}  -suppress 
set_msg_config  -ruleid {9}  -id {Synth 8-6014}  -suppress 
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bup48/Documents/VivadoProjects/RISCPROCESSOR-8/RISCPROCESSOR-8.cache/wt [current_project]
set_property parent.project_path C:/Users/bup48/Documents/VivadoProjects/RISCPROCESSOR-8/RISCPROCESSOR-8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu106:part0:2.2 [current_project]
set_property ip_output_repo c:/Users/bup48/Documents/VivadoProjects/RISCPROCESSOR-8/RISCPROCESSOR-8.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/bup48/Downloads/MUX.v
  C:/Users/bup48/Downloads/data_memory.v
  C:/Users/bup48/Downloads/Memorypath.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Memorypath -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Memorypath.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Memorypath_utilization_synth.rpt -pb Memorypath_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
